spring:
  data:
    mongodb:
      uri: mongodb+srv://heshanu97:test@cluster0.f6bnq.mongodb.net/activitydb?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true
      connection-timeout: 5000
      socket-timeout: 3000
  application:
    name: activity-service # Use lowercase with hyphens for consistency

server:
  port: 8082

# Improved logging configuration
logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com.mongodb: INFO
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG

eureka:
  client:
    instance:
      nonSecurePort: ${server.port}
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

